#!/bin/bash
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
function log() {
    logger -t ccdgut-auth ${1}
    echo ${1}
}

if [ "${url_prefix}" == "" ]; then
    url_prefix="http://192.168.100.1"
fi

username=${1}
password=${2}

PIDFILE="/tmp/ccdgut-auth-${username}.pid"

oldPid=$(cat ${PIDFILE})

if [ "${oldPid}" != "" ] && [ "${oldPid}" -gt "0" ] && ps -p ${oldPid} | grep "ccdgut-auth";then
    log "Stop old process: ${oldPid}"
    kill -9 ${oldPid}
fi

echo ${$} > ${PIDFILE}

while true; do
    sleepTime=30

    content=$(curl --connect-timeout 10 -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' ${url_prefix})
    if [ "${?}" == "0" ] && ! echo ${content} | grep "uid=" > /dev/null 2>&1;then
        curl "${url_prefix}/a70.htm" \
            --connect-timeout 10 \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' \
            -H "Referer: ${url_prefix}/a70.htm" \
            --data 'DDDDD='${username}'&upass='${password}'&R1=0&R2=&R3=0&R6=0&para=00&0MKKey=123456&buttonClicked=&redirect_url=&err_flag=&username=&password=&user=&cmd=&Login=&v6ip=' | grep "errorMsgObj.DispTFM();" > /dev/null

        if [ "${?}" != "0" ];then
            # Send signal to zte-client, so as to do China Telecom web authentication
            # killall -USR1 zte-client
            log "Login successfully"
        else
            sleepTime=3
            log "Login failed"
        fi
    else
        log "Already logined"
    fi

    sleep ${sleepTime}
done
